import './globals.css'
import {TrpcProvider} from "@/utils/TrpcProvider";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='h-14 bg-gradient-to-r from-violet-500 to-fuchsia-500'>
        <TrpcProvider>
           {children}
        </TrpcProvider>
      </body>
    </html>
  )
}
